# Demo {#sec-demo}

We provide a demonstation with

-   anonymised datasets from our pilot study (done in french)

-   complete code (`*.R`and `*.Rmd`) slightly modify (the codes retrieving data from REDCap and updating texts are not run)

-   final output so you can see the reports generated by the code

You can also run it on your machine to make sure it works before starting your own project.

::: {.callout-warning appearance="simple"}
Sometimes the code might not run smoothly if one of the packages (or R) has been updated.

You can :

-   run the code from the beginning so the variables and .RData have the most recent format

-   look on [Stackoverflow](https://www.stackoverflow.com) if someone had the same problem

-   try to narrow down what causes the problem and ask a question yourself with a reproducible example (reprex) on [Stackoverflow](https://www.stackoverflow.com)

-   wait a week or two so the problem is spotted and hope a solution was found
:::

Details of the method for the demo data have been published.
