# Pre-requisites {#sec-pre-requisites}

To start using the toolkit for your *fast--track Delphi* project, you will need to:

-   install RStudio and R - see [Hands-On Programming with R - Appendix A](https://jjallaire.github.io/hopr/a1-starting.html)

-   get some packages

-   get a token for your REDCap project if you are using one, and update some files (not necessary to explore the demo)

## Get some packages {#sec-get-some-packages}

You will need to run the following *chunks (lines of executable code)*

-   [ ] Install pacman unless you already have it : simpler to call libraries and keep them up-to-date

    ``` r
    ## install it if not already there
    if (!require("pacman")) install.packages("pacman") 
    ```

-   [ ] Load the following packages with `pacman::p_load` (it will 1. install package if not installed and keep it up-to-date, 2. call the library)

    ``` r
    pacman::p_load(
        bookdown,
        crayon,
        data.table,
        flextable,
        formattable,
        fs,
        ftExtra,
        ggplot2,
        haven,
        here,
        magrittr,
        officedown,
        patchwork,
        purrr,
        REDCapR,
        sjlabelled,
        sjmisc,
        sjPlot,
        stringr,
        tidyverse,
        writexl)

    ## install.packages("remotes") ## If it's not already installed.
    remotes::install_github("OuhscBbmc/OuhscMunge")
    ```

-   [ ] Install delphiFT

    > ***TODO** : NOT READY YET, but will need to add instructions and make sure it works*

    ``` r
    Download as a zip file (click on green button Code), and unzip locally
      or
    remotes::install_github("Unisante/delphiFT") 
    ```

## Token to access your REDCap Project *(not for the demo)* {#sec-token-to-access-your-redcap-project}

The steps below will allow the codes to automatically retrieve your personal tokens corresponding to your REDCap project, for each of the two rounds (dft2 and dft3), whilst avoiding sharing them.

-   [ ] Obtain your tokens from the API Menu in [**`REDCap`**](https://projectredcap.org/) - talk with your REDCAp Admin if necessary

-   [ ] Create a local file **outside** the RStudio project, so no one else can use it, and give it a name *token_delphi_ft_projectname.R* (replace *projectname* by your project name)

-   [ ] Copy-paste the following lines in this new local file:

    ``` r
    uri_redcap_your_institution <- "<https://XXXXXXXXX>" 
    token_dft2_your_project <- "YYYYYYYYYYYYYYYY"
    token_dft3_your_project <- "ZZZZZZZZZZZZZZZZ"
    ```

-   [ ] Replace *your_institution* by your institution name, *your_project* by a short project name, and update *XXX*, *YYY* and *ZZZ* with your details from the API Menu in [**`REDCap`**](https://projectredcap.org/)

-   [ ] Open the file `./code/dft2/000_parameters.R` and update the following lines in **0. general elements**:

    1.  Replace `path/to/your/token_file.R` with the actual path to your token file and

    2.  Replace *uri_redcap_your_institution* and *token_dft2_project_name* with your institution and short project name (same as previous point).
