# Demo {#sec-demo}

We provide a demonstration with

-   anonymised dataset and metadata from our pilot study (done in french)

-   complete code (`*.R`and `*.Rmd`) slightly modified (the codes retrieving data from REDCap and updating texts are not run)

-   final output so you can see the reports generated by the code

You can also run it on your machine to make sure it works before starting your own project.

::: {.callout-warning appearance="simple"}
Sometimes the code might not run smoothly if one of the packages (or R) has been updated.

You can :

-   run the code from the beginning so the variables and .RData have the most recent format

-   look on [Stackoverflow](https://www.stackoverflow.com) if someone had the same problem

-   try to narrow down what causes the problem and ask a question yourself with a reproducible example (reprex) on [Stackoverflow](https://www.stackoverflow.com)

-   wait a week or two so the problem is spotted and hope a solution was found
:::

## Download the demo

[Delphi Fast Track : code with demo data and results](https://github.com/Unisante) is available on GitHub.



## Look at the reports

In `./output/reports/`, you will find the reports which are **editable word documents**:

-   a generic report and individualised reports for the second round (dft2)

-   a generic report and individualised reports for the third round (dft3)

-   an overall executive summary



## Understand the structure

### Folders content

- `analysis`  
    
    - **Rmd files**: one common for the introductory text for the method section and the others in subfolders for each round (dft2, dft3) and for the overall report
    
    - **docx templates**: one in each subfolder
    

- `code` : **R files** that are common and others in two subfolders for each round (dft2, dft3) - the numbers indicate the order in which they are run

- `data`: data and metadata **RData files** in subfolders for each round (dft2, dft3) and for the raw data
    
    
- `output`: subfolders `checks`, `png`, `RData`, `reports`
    
- `texts_intro`: **docx** with separate introductory texts that will be 'imported' into the reports


### Files to run
- `00_run_ME_once_to_create_structure.R`: not needed for demo

The following files at root can be run one at a time. 

- `0_run_ME_dft2_demo.R`

- `0_run_ME_dft3_demo.R`

- `0_run_ME_overall_demo.R`


They will produce : 

- intermediate tables saved in `./output/RData/` and `./output/checks/`

- miniplots saved in `./output/png/`

- word reports saved in `./output/reports/`




## Discover the functions {#sec-discover-functions}

We chose to keep the functions used in this analyses in a R file because it is easier to toy with than a proper package.

We strongly recommend that you become familiar with the functions developed for this analysis in code `./code/00_functions.R`. This code will also run each time `./code/000_parameters.R`.
