# Demo {#sec-demo}

We provide a demonstration with

-   the anonymised dataset and metadata from our pilot study (done in french) [@velardecrézé2023]

-   the complete code (`*.R` and `*.Rmd`), slightly modified (the codes retrieving real - non-anonymized - data from REDCap and updating introductive texts are not run)

-   the final output, so you can go through the reports generated by the code

You can run this demonstration on your machine to make sure it works before starting your own project.

::: {.callout-warning appearance="simple"}
Sometimes the code might not run smoothly if one of the packages (or R) has been updated.

Should this occur, you can :

-   run the code from the beginning so the variables and .RData files have the most recent format

-   look on [Stackoverflow](https://www.stackoverflow.com) if someone had the same problem

-   try to narrow down what causes the problem and ask a question yourself with a reproducible example (reprex) on [Stackoverflow](https://www.stackoverflow.com)

-   wait a week or two so the problem is spotted and hope a solution was found
:::

## Download the demo

Our [fast-track Delphi: code with demo data and results](https://github.com/Unisante) is available on GitHub.

## Look at the reports

In `./output/reports/`, you will find the reports which are **editable word documents**:

-   one generic report and x individualized reports - one for each expert - for the second round (dft2)

-   one generic report and x individualized reports - one for each expert - for the third round (dft3)

-   an overall executive summary synthesizing results from the second and third rounds

## Understand the structure

### Folders content

-   `analysis`

    -   **Rmd files**: one common for the introductory text for the method section and the others in subfolders for each round (dft2, dft3) and for the overall report

    -   **docx templates**: one in each subfolder

-   `code` : **R files** that are common to both rounds and others in two subfolders for each round (dft2, dft3) - the numbers indicate the order in which they are run

-   `data`: data and metadata **RData files** for the raw data and in subfolders for each round (dft2, dft3)

-   `output`: subfolders `checks`, `png`, `RData`, `reports`. Final reports in an editable word format are located in the subfolder `reports` (generic and individualized result reports).

-   `texts_intro`: **docx** with separate introductory texts that will be 'imported' into the reports

### Files to run

-   `00_run_ME_once_to_create_structure.R`: not needed for demo (the folder structure of the project is already created).

The following files at root can be run one at a time:

-   `0_run_ME_dft2_demo.R`

-   `0_run_ME_dft3_demo.R`

-   `0_run_ME_overall_demo.R`

They will produce :

-   intermediate tables saved in `./output/RData/` and `./output/checks/`

-   miniplots saved in `./output/png/`

-   word reports saved in `./output/reports/`

## Discover the functions {#sec-discover-functions}

We chose to keep the functions used in these analyses in a R file because it is easier to toy with.

We strongly recommend that you become familiar with the functions developed for this analysis in code `./code/00_functions.R`. This code will also run each time `./code/000_parameters.R`.
