# Start your project {#sec-start-your-project}

## Pre-requisites {#sec-pre-requisites-start}

-   [ ] To start your own project, download the [fast-track Delphi: code only](https://github.com/Unisante/delphi-fast-track) available on GitHub.

-   [ ] Make sure you have done the steps presented in @sec-pre-requisites (install RStudio and R + get some packages)

-   [ ] Make sure you went through and understood @sec-understand-type-of-questions

-   [ ] Make sure you have prepared the structure of your projects in [**`REDCap`**](https://projectredcap.org/) and got a token to access them according to the instructions in @sec-instructions-for-redcap

## Understand the structure {#sec-understand-the-structure-start}

You are now ready to start your own project. Below you will find the detail of the structure - folders, subfolders and files - when you start your project, and what will be added by the end. The demo you have been through in @sec-demo shows a project when it is finished.

::: callout-tip
You can use [`fs::dir_tree()`](https://fs.r-lib.org/reference/dir_tree.html) to see the structure at any time.
:::

### At the begining {#sec-at-the-begining}

When you start your project (i.e., when downloading the [fast-track Delphi: code only](https://github.com/Unisante/delphi-fast-track) on GitHub), you will have the following structure:

``` r
├── 000_READ_ME_first.md
├── 00_run_ME_once_to_create_structure.R
├── 0_run_ME_dft2.R
├── 0_run_ME_dft3.R
├── 0_run_ME_overall.R
├── _xml_for_redcap
│   ├── DelphiFTTemplateRound_2.REDCap.xml
│   ├── DelphiFTTemplateRound_3.REDCap.xml
├── analysis
│   ├── 00_child_intro_method.Rmd
│   ├── dft2
│   │   ├── dft2_child_section.Rmd
│   │   ├── dft2_report_generic.Rmd
│   │   ├── dft2_report_per_participant.Rmd
│   │   └── template-bookdown.docx
│   ├── dft3
│   │   ├── dft3_child_section.Rmd
│   │   ├── dft3_report_generic.Rmd
│   │   ├── dft3_report_per_participant.Rmd
│   │   └── template-bookdown.docx
│   └── overall
│       ├── delphiFT_Overall_FigureFlow.pptx
│       ├── ExecutiveSummary_figure_Target-Consensus.png
│       ├── ExecutiveSummary_figure_Target-NoConsensus.png
│       ├── overall_executive_summary.Rmd
│       └── template_exec_summary_bookdown.docx
├── code
│   ├── 000_parameters.R
│   ├── 00_functions.R
│   ├── 00_update_texts_intro.R
│   ├── 03a_create_flextable_results_type_1_generic.R
│   ├── 03b_create_flextable_results_type_2_3_generic.R
│   ├── 04a_create_flextable_results_type_1_participants.R
│   ├── 04b_create_flextable_results_type_2_3_participants.R
│   ├── 06_prepare_tables_combined_round_2_3.R
│   ├── dft2
│   │   ├── 01a_dft2_update_data_with_REDCapR.R
│   │   ├── 01b_dft2_recode_data.R
│   │   ├── 01c_dft2_define_cols.R
│   │   ├── 02a_dft2_prepare_tables_without_participant_id.R
│   │   ├── 02b_dft2_prepare_tables_participants.R
│   │   └── 05_dft2_to_render_individual_reports.R
│   └── dft3
│       ├── 01a_dft3_update_data_with_REDCapR.R
│       ├── 01b_dft3_recode_data.R
│       ├── 01c_dft3_define_cols.R
│       ├── 02a_dft3_prepare_tables_without_participant_id.R
│       ├── 02b_dft3_prepare_tables_participants.R
│       └── 05_dft3_to_render_individual_reports.R
├── texts_intro
│   ├── .. several *.docx files
├── token_delphi_ft_this_project.R.example
└── delphi_ft.Rproj
```

### At the end {#sec-at-the-end}

The following will appear during the analysis and report production.

``` r
├── token_delphi_ft_this_project.R
├── data
│   ├── dft2
│   │   ├── dft2_data_clean.RData
│   │   ├── dft2_lookup_final.RData
│   │   └── dft2_lookup_value_labels_final.RData
│   ├── dft3
│   │   ├── dft3_data_clean.RData
│   │   └── dft3_lookup_final.RData
│   └── redcap_data_raw
│       ├── dft2_data_redcapr_raw.RData
│       ├── dft2_metadata.RData
│       ├── dft3_data_redcapr_raw.RData
│       └── dft3_metadata.RData
├── output
│   ├── checks
│   │   ├── .. several *.xlsx files
│   ├── png
│   │   ├── .. several *.png files
│   ├── RData
│   │   ├── dft2_dt_comments_m.RData
│   │   ├── dft2_type0_zz1.RData
│   │   ├── dft2_type1_zz_combined.RData
│   │   ├── dft2_type2_zz1.RData
│   │   ├── dft2_type3_zz1.RData
│   │   ├── dft3_dt_comments_m.RData
│   │   ├── dft3_type1_zz_combined.RData
│   │   └── type1_zz_combined_round_2_3.RData
│   └── reports
│       ├── dft2
│       │   ├── dft2_report_generic_YYYY-MM-DD.docx
│       │   └── report_by_participant
│       │       ├──  dft2_report_participant_1_YYYY-MM-DD.docx
│       │       ├── ...
│       ├── dft3
│       │   ├── dft3_report_generic_YYYY-MM-DD.docx
│       │   └── report_by_participant
│       │       ├──  dft3_report_participant_1_YYYY-MM-DD.docx
│       │       ├── ...
│       └── overall
│           └── dft_overall_executive_summary_YYYY-MM-DD.docx
.
.
.
```

## Create the structure of your project {#sec-create-structure-project}

-   [ ] Run `00_run_ME_once_to_create_structure.R`

This will create the predefined set of folders and subfolders - detailed above in @sec-understand-the-structure-start - within your main project folder.

::: callout-warning
We strongly advise keeping this predefined structure as it is. If you still choose to modify it, you will need to revise every path in the `*.R` and `*.Rmd` files.
:::

## Update parameters {#sec-update-parameters}

-   [ ] Open `./code/000_parameters.R` and update with your topical inputs, as necessary

## Update the word templates {#sec-update-word-templates}

This project uses `MS Word` templates in order to build the generic and individualized reports. The autonumbering will be created by [`bookdown`](https://pkgs.rstudio.com/bookdown/).

-   [ ] Update the templates to suit your needs in each subfolder :

    -   `./analysis/dft2/template-bookdown.docx`

    -   `./analysis/dft3/template-bookdown.docx`

    -   `./analysis/doverall/template_exec_summary_bookdown.docx`

Please refer to the [Officeverse manual](https://ardata-fr.github.io/officeverse/) to see how to do it.

## Update introductory texts {#sec-update-texts-introduction}

These texts are word documents with one or two paragraphs, sometimes images that will be inserted at the beginning of the reports. They will be updated in several steps, once some of the results are available.

-   [ ] Prepare the word documents in advance to gain time

::: {.callout-caution appearance="simple"}
-   Do not leave a blank line at the beginning of the text, nor at the end

-   Headers are not needed in these texts as they will be provided in Rmd files
:::

-   [ ] Store them on the server in the folder defined in `./code/000_parameters.R` (called `path_texts_intro_server`).

-   [ ] Run `./code/00_update_texts_intro.R`

Congratulations: **you are now ready** to conduct round 1 (expert meeting following an adapted Nominal Group Technique (NGT) procedure - not detailed in this userguide) and round 2 with your panel of experts!
