project:
  type: book

book:
  title: "Fast-track Delphi: user guide"
  description: | 
    A user guide for the fast-track Delphi toolkit.
  author:
  - name: Olivier Duperrex
    orcid: 0000-0002-0932-6846
    attributes:
      corresponding: true
    affiliations:
    - id: unisante
      name: Unisanté
      address: Route de Berne 113
      city: Lausanne
      country: Suisse
      postal-code: CH-1010
    - id: unige
      name: Institute of Global Health, University of Geneva
      city: Geneva
      country: Suisse
  - name: Camille Velarde Crézé
    orcid: 0000-0002-4686-9401
    affiliations:
    - ref: unisante
  date: today
  search: true
  repo-url: https://github.com/Unisante/
  downloads: [pdf, epub]
  sharing: [facebook, linkedin]
  chapters:
    - index.qmd
    - part: "Get ready"
      chapters:
        - 01_prerequisites.qmd
        - 02_questions.qmd
        - 03_instructions_REDCap.qmd
    - part: "Explore the demo"
      chapters:
        - 04_demo.qmd
    - part: "Create your own project"
      chapters: 
        - 05_structure.qmd
        - 06_start_your_project.qmd
        - 07_round_2.qmd
        - 08_round_3.qmd
        - 09_overall.qmd
    - references.qmd
  appendices:
    - resources.qmd
  cover-image: _img/Ex_type1question_dft2-s16_NoHeader.png
  page-footer: 
    left: "Fast-track Delphi: user guide - version 0.3 - March 2023"
    center: "![](_img/logo_unisante_footer.png){width=50%}"

citation: true
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
  docx: 
    reference-doc: _templates/template-bookdown.docx

editor: visual



