project:
  type: book

book:
  title: "Fast-track Delphi: user guide"
  description: | 
    A user guide for the fast-track Delphi toolkit.
  author:
  - name: Olivier Duperrex
    orcid: 0000-0002-0932-6846
    attributes:
      corresponding: true
    affiliations:
    - id: unisante
      name: Unisanté
      address: Route de Berne 113
      city: Lausanne
      country: Suisse
      postal-code: CH-1010
    - id: unige
      name: Institute of Global Health, University of Geneva
      city: Geneva
      country: Suisse
  - name: Camille Velarde Crézé
    orcid: 0000-0002-4686-9401
    affiliations:
    - ref: unisante
  date: last-modified
  date-format: "[Last Updated in] MMMM, YYYY"
  search: true
  doi: "10.16909/dataset/39"
  repo-url: https://github.com/Unisante/delphi-fast-track-user-guide
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: "Get ready"
      chapters:
        - 01_prerequisites.qmd
        - 02_questions.qmd
    - part: "Explore the demo"
      chapters:
        - 03_demo.qmd
    - part: "Create your own project"
      chapters: 
        - 04_REDCap.qmd
        - 05_start_your_project.qmd
        - 06_round_2.qmd
        - 07_round_3.qmd
        - 08_overall.qmd
  appendices:
    - resources.qmd
  page-footer: 
    left: "Fast-track Delphi: user guide - v0.6 - Dec 2024"
    center: "![](_img/logo_unisante_footer.png){width=25%}"


citation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
  docx: 
    reference-doc: _templates/template-bookdown.docx
  epub:
    cover-image: _img/logo_unisante_RVB_2lignes.png
    toc: true
    
editor: visual



