project:
  type: book

book:
  title: "Delphi fast-track : user guide"
  author:
  - name: Olivier Duperrex
    orcid: 0000-0002-0932-6846
    attributes:
      corresponding: true
    affiliations:
    - id: unisante
      name: Unisanté
      address: Route de Berne 113
      city: Lausanne
      country: Suisse
      postal-code: CH-1010
    - id: unige
      name: Institute of Global Health, University of Geneva
      city: Geneva
      country: Suisse
  - name: Camille Velarde Crézé
    orcid: 0000-0002-4686-9401
    affiliations:
    - ref: unisante
  date: today
  search: true
  repo-url: https://github.com/Unisante/
  downloads: [pdf, epub]
  sharing: [facebook, linkedin]
  chapters:
    - index.qmd
    - part: "Get ready"
      chapters:
        - 01_intro.qmd
        - 02_questions.qmd
    - part: "Explore the demo"
      chapters:
        - 03_demo.qmd
        - 04_structure.qmd
    - part: "Create your own project"
      chapters: 

        - 05_start_your_project.qmd
        - 06_dft2.qmd
        - 07_dft3.qmd
        - 08_overall.qmd

    - references.qmd
  appendices:
    - tools.qmd
    - resources.qmd
  cover-image: _img/screenshot_individual_fr.png
  page-footer: 
    left: "Delphi fast-track : user guide - version 0.2 - Feb 2023"
    center: "![](_img/logo_unisante_footer.png){width=50%}"


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
  docx: 
    reference-doc: _templates/template-bookdown.docx

editor: visual



